stages:
  - build
  - verify

build:
  image: maven:3.6.3-jdk-8
  stage: build
  script:
    - mvn compile

integration_tests:
  image: maven:3.6.3-jdk-8
  stage: verify
  script:
    - mvn '-Dtest=ee.icd0004.project.integration.*Test' test
mock_test:
  image: maven:3.6.3-jdk-8
  stage: verify
  script:
    - mvn '-Dtest=ee.icd0004.project.mock.*Test' test
unit_tests:
  image: maven:3.6.3-jdk-8
  stage: verify
  script:
    - mvn '-Dtest=ee.icd0004.project.unit.*Test' test
